color = input("Enter your favourite color (green,blue,black,white,none) : ")
age = int(input("Enter your age : "))
alcohol = bool(input("Do u drink alcohol ? (True/False)"))
answer = float(input("How much  if 1/2 ?  : "))
print(f"My favourite color is {color} , My age is : {age} , i drink alcohol ? {alcohol} , My answer is :{answer}")
print(color, age, alcohol, answer, sep=" , ")
print("Color : ", color, " My age is : ", age, " Alcohol  : ", alcohol, " Answer :  ", answer,)
print("Color " + str(color) + " My age is " + str(age) + " Alcohol : " + str(alcohol) + "Answer : " + str(answer))
print("My Favourite color is {} My age is {} Do u think i am drinking?{} My answer is {}".format(color, age, alcohol, answer),)
